### ISSUE TITLE
Code won't run!

### ISSUE THREAD

**Issue by shadowelecman** [SumeetBatra/Alzowaid_Batra_CSCI2270_FinalProject#2]
Hey guys, I love your concept! Sadly I tried to run your code but I got the following errors:
main.cpp: In function ‘int main()’:
main.cpp:43:14: error: aggregate ‘std::ifstream inFile’ has incomplete type and cannot be defined
     ifstream inFile;
              ^
main.cpp:44:14: error: aggregate ‘std::ifstream inFile2’ has incomplete type and cannot be defined
     ifstream inFile2;
              ^
main.cpp:57:18: error: ‘argv’ was not declared in this scope
     inFile2.open(argv[1]);
                  ^
Graph.cpp: In member function ‘void Graph::BFTraversalLabel(std::string, int)’:
Graph.cpp:14:5: error: ‘queue’ was not declared in this scope
     queue <vertex*> q;
     ^
Graph.cpp:14:18: error: expected primary-expression before ‘*’ token
     queue <vertex*> q;
                  ^
Graph.cpp:14:19: error: expected primary-expression before ‘>’ token
     queue <vertex*> q;
                   ^
Graph.cpp:14:21: error: ‘q’ was not declared in this scope
     queue <vertex*> q;
                     ^
Graph.cpp:15:39: error: ‘findVertex’ was not declared in this scope
     vertex* v =findVertex(startingCity);//the start aka Denver ..
                                       ^
Graph.cpp: In member function ‘void Graph::shortestPath(std::string, std::string)’:
Graph.cpp:104:17: warning: overflow in implicit constant conversion [-Woverflow]
     int INT_MAX=9999999999999999;

It looks like your code doesn't include fstream or queue, and you call a function on line 15 in graph.cpp that doesn't exist. Also, there are large chunks of the original assignment that are in your code but don't have anything to do with your project that keep it from running. Please sort the kinks out so I can try your code, it sounds cool!

**Comment by RawanAlzowaid** [comment]
Thank you  !
I already fixed all the problems, hopefully it will work perfectly now ,
please try evaluation it again.

Thanks.

Regards,
Rawan.

**Comment by shadowelecman** [comment]
Thanks for the prompt answer! I redid your evaluation, I found a bug or two but it mostly ran just fine. Me not being able to open it was partially user error because I was opening your project with Geany, you know how it is.
